### ISSUE TITLE
Cannot import the module

### ISSUE THREAD

**Issue by tadejstanic** [Akryum/vue-resize#1]
I wanted to try this plugin but unfortunately I couldn't import the module in my project.

If I run:

```
import Vue from 'vue'
import app from './app.vue'
import VueResize from 'vue-resize'

Vue.use(VueResize)

new Vue({
  el: '#app',
  render: h => h(app)
})
```

I get:

```
Module parse failed: /Users/ts/Work/vue-resize-test/node_modules/vue-resize/index.js Unexpected token (1:20)
You may need an appropriate loader to handle this file type.
| export default from './dist/vue-resize'
| export * from './dist/vue-resize'
| import './dist/vue-resize.css'

 @ ./index.js 3:0-35
 @ multi (webpack)-hot-middleware/client.js?reload=true index.js

> Open http://localhost:4000
```

**Comment by Akryum** [comment]
Did you setup css-loader in the webpack config?

**Comment by tadejstanic** [comment]
I think this isn't the problem. I'm using `vue build` from `vue cli` in order to test your component. I found this is the fastest way to try third party components without setting up all the dev env.

So if I run [vue build](https://github.com/vuejs/vue-cli/blob/master/docs/build.md) index.js where I import vue-resize module then the various problems begin depending what kind of import I choose (default, source, distribution).

**Comment by adrienfourel** [comment]
I'm facing the same problem.
I'm using [vuejs-template/webpack-simple](https://github.com/vuejs-templates/webpack-simple) and I added this loader to my webpack config :

```
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
```

When importing a single file, it seems to work but I never found how to import css from npm packages. I'm quite new with webpack so I'm probably missing something.

**Comment by gigony** [comment]
I have the same problem.
If I import source ( import { ResizeObserver } from 'vue-resize/src' ) even after installing babel stage-0 preset, I see the following errors.

> Uncaught ReferenceError: VERSION is not defined
>     at Object.eval (webpack:///./~/vue-resize/src/index.js?:22)
>     at eval (webpack:///./~/vue-resize/src/index.js?:39)
>     at Object.<anonymous> (app.js:800)
>     at __webpack_require__ (vendor.js:694)
>     at fn (vendor.js:115)
>     at eval (webpack:///./client/views/Home.vue?./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0:2)
>     at Object.<anonymous> (app.js:442)
>     at __webpack_require__ (vendor.js:694)
>     at fn (vendor.js:115)
>     at eval (webpack:///./client/views/Home.vue?:7)

FYI, I am using https://github.com/vue-bulma/vue-admin/blob/master/build/webpack.base.conf.js for webpack configuration.

And if I import dist (import { ResizeObserver } from 'vue-resize' ) then I see the following error even after installing css-loader (install module and change webpack.base.conf.js).

> ERROR in ./~/vue-resize/index.js
> Module parse failed: /usr/app/node_modules/vue-resize/index.js Unexpected token (1:20)
> You may need an appropriate loader to handle this file type.
> | export default from './dist/vue-resize'
> | export * from './dist/vue-resize'
> | import './dist/vue-resize.css'
>  @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./client/views/Home.vue 58:0-44
>  @ ./client/views/Home.vue
>  @ ./client/router/index.js
>  @ ./client/app.js
>  @ ./client/index.js
>  @ multi ./build/dev-client ./client/index.js

**Comment by Neru** [comment]
I also had the initial problem. But when I added the babel dependencies (https://github.com/Akryum/vue-resize/blob/master/package.json#L31-L35) to my package.json, the babel-loader (https://github.com/Akryum/vue-resize/blob/master/config/webpack.base.config.js#L25-L28) to my webpack config and the .babelrc file (https://github.com/Akryum/vue-resize/blob/master/.babelrc) to my root folder, it compiled correctly. I'm using node 6.10.3, webpack 2.6.0, and vue 2.3.3.

**Comment by SharadKumar** [comment]
This fails with `nuxtjs`, with above error: `You may need an appropriate loader to handle this file type`. I have added many components to the project using nuxt, but only this one fails. Any clues how to fix?

**Comment by Akryum** [comment]
I was successfully able to use the plugin in nuxt 1.0.0-rc3 using vue-resize 0.1.4
