### ISSUE TITLE
New width and height in event

### ISSUE THREAD

**Issue by ybilik** [Akryum/vue-resize#10]
Hello, couldn't it be useful to have the new width/height as parameters of the notify event ?
```javascript
handleResize: function(evt) {
    console.log("new size is " + evt.width + "x" + evt.height);
}
```
(even if these dimensions can be retrieved with a call to `offsetWidth` or similar property).

**Comment by dllsystem** [comment]
https://github.com/dllsystem/vue-resize

**Comment by robokozo** [comment]
It'd be great if the notify event emitted this extra meta data.

**Comment by Akryum** [comment]
https://github.com/Akryum/vue-resize/commit/cbc7c729c58765e227d69cba1fb8148fcc8fb0d8
