### ISSUE TITLE
Does not work with ie11 anymore (v1.0.0)

### ISSUE THREAD

**Issue by aulonm** [Akryum/vue-resize#241]
Hello!

I've been using your package for a couple of years now but since version v1.0.0 it stopped working with IE11.

I've reproduced the bug here but not entirely sure what has happened

https://github.com/aulonm/vue-resize-ie11-bug

**Comment by yavisht** [comment]
Confirmed and downgraded to 0.5.0 as a temp fix

https://github.com/Akryum/v-tooltip/issues/656#issuecomment-796260916

**Comment by aulonm** [comment]
I think the problem lies in the build step.Haven't managed to narrow it down, but I don't think it's actually transpiling the code and because of that it doesn't work on older browsers
