### ISSUE TITLE
Allow debouncing the event

### ISSUE THREAD

**Issue by mika76** [Akryum/vue-resize#9]
Currently it can send a whole bunch of events while resizing when really all you need is the last one. How about giving an optional debounce time where the event will only throw after that trigger?

ie: https://codeburst.io/throttling-and-debouncing-in-javascript-b01cad5c8edf

**Comment by ybilik** [comment]
Hello, couldn't it be useful to have the new width/height as parameters of the notify event ?

**Comment by slidenerd** [comment]
Even better why not use the ResizeObserver instead of the resize event?

**Comment by Akryum** [comment]
> Even better why not use the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) instead of the resize event?

Doesn't work on IE :sweat_smile:

**Comment by Akryum** [comment]
> Currently it can send a whole bunch of events while resizing when really all you need is the last one. How about giving an optional debounce time where the event will only throw after that trigger?
> 
> ie: https://codeburst.io/throttling-and-debouncing-in-javascript-b01cad5c8edf

I don't intend to add throttling or debouncing in the library, as it can easily be done on user side.
